spring:
  application:
    name: config-server
  profiles:
    active: native # Sets the spring profile associated with the backend repository (filesystem)
  cloud:
    config:
      server:
      #Local configuration: This locations can either of classpath or locations in the filesystem.
        native:
         #Reads from a specific filesystem folder
        search-locations: classpath:/config
        # file://${user.home}/config-repo
        # file:///{FILE_PATH}
server:
  port: 8071

encrypt:
  key: secretkey