spring.application.name: cloud-dashboard
server.port: 8090
spring:
  security.user:
      name: "admin"
      password: "admin"

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management.security.enabled: false
