spring.application.name: order-service
server.port: 9000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  register-with-eureka: true
  fetch-registry: true
  instance:
    appname: order-service
