spring.application.name: order-service
server.port: 9000

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always

#basic auth creddentials
#spring.security.user:
#  name: "client"
#  password: "client"

#configs to connect to a secured server
spring.boot.admin.client:
  url: http://localhost:8090
  username: "admin"
  password: "admin"
  #configs to give secured server info
#  instance.metadata.user:
#    name: ${spring.security.user.name}
#    password: ${spring.security.user.password}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    appname: order-service
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      default-zone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  register-with-eureka: true
  fetch-registry: true
